# lang.py
# Diccionario de traducciones para el sistema bilingüe

TRANSLATIONS = {
    'es': {
        'title': '🍅 Sistema de Detección de Enfermedades en Tomate',
        'subtitle': 'Comparación de modelos de Deep Learning Clásicos e Híbridos para diagnóstico automático',
        'sidebar_title': '⚙️ Configuración',
        'lang_select': '🌐 Idioma',
        'mode_select': '🚀 Modo de Análisis',
        'mode_fast': 'Rápido (Clásicos)',
        'mode_full': 'Completo (Híbridos + Clásicos)',
        'mode_fast_desc': 'Ideal para dispositivos móviles o predicciones instantáneas.',
        'mode_full_desc': 'Máxima precisión. Incluye SVM y Random Forest.',
        'tab_inference': '🔬 Análisis Inteligente',
        'tab_dashboard': '📊 Dashboard Global',
        'tab_stats': '📐 Pruebas Estadísticas',
        'tab_eda': '📈 Análisis Exploratorio (EDA)',
        'tab_train': '⚙️ Laboratorio de Modelos',
        'tab_chat': '🤖 Asistente Virtual',
        'inference_desc': 'Sube la imagen de una hoja de tomate para obtener un diagnóstico basado en el consenso de todos nuestros modelos.',
        'upload_img': '📸 Cargar Imagen',
        'upload_label': 'Selecciona una imagen de hoja de tomate',
        'btn_analyze': '🔍 Analizar Imagen',
        'loading': 'Analizando con',
        'consensus_title': '👑 Predicción Final (Consenso por Confianza)',
        'severity': 'Severidad',
        'confidence_acc': 'Acumulado de Confianza',
        'treatment_btn': '🛡️ Ver Tratamiento Recomendado',
        'water': 'Riego',
        'chem': 'Químico',
        'prev': 'Prevención',
        'model_details': '🤖 Detalles por Modelo y Mapas de Calor',
        'prediction': 'Predicción',
        'heat_btn': 'Generar Mapa de Calor para',
        'export_title': '📄 Exportar Reportes',
        'btn_pdf': 'Descargar PDF',
        'btn_word': 'Descargar Word',
        'btn_excel': 'Descargar Excel',
        
        # Training Tab
        'train_title': '⚙️ Laboratorio de Entrenamiento (PyTorch)',
        'train_desc': 'Entrena redes neuronales en tiempo real desde el navegador. Los hiperparámetros impactarán el proceso en vivo.',
        'train_settings': 'Parámetros de Entrenamiento',
        'train_epochs': 'Épocas',
        'train_lr': 'Tasa de Aprendizaje (Learning Rate)',
        'train_batch': 'Batch Size',
        'train_model': 'Modelo Base',
        'btn_start_train': '🚀 Iniciar Entrenamiento',
        'training_progress': 'Progreso de Entrenamiento',
        'epoch': 'Época',
        'loss': 'Pérdida (Loss)',
        'accuracy': 'Precisión (Accuracy)',
        'train_done': '¡Entrenamiento Finalizado! Modelo guardado.',
        
        # Chatbot
        'chat_title': '🤖 Asistente Virtual Agrónomo',
        'chat_desc': 'Hazme preguntas sobre las enfermedades del tomate, tratamientos o cómo usar este sistema.',
        'chat_input': 'Escribe tu pregunta aquí...',
        'chat_welcome': '¡Hola! Soy tu asistente agrónomo virtual. ¿En qué te puedo ayudar hoy?',
        
        # Errors & Warnings
        'err_no_img': 'Por favor sube una imagen primero.',
        'err_heat': 'Los mapas de calor no están disponibles para modelos híbridos.',
        'err_predict': 'Error al realizar la predicción',
        
        # Dashboard
        'dash_title': '📊 Dashboard Global de Rendimiento',
        'dash_desc': 'Vista exhaustiva de las métricas de rendimiento, validación y capacidad discriminativa del sistema.',
        'dash_hist': '📈 Historial de Entrenamiento (Accuracy vs Loss)',
        'dash_hist_info': '💡 **Curvas de Aprendizaje:** Demuestra que el modelo convergió correctamente sin sufrir de *Overfitting* (sobreajuste).',
        'dash_cm': '🎯 Matriz de Confusión (Ensemble)',
        'dash_cm_info': '💡 **Matriz de Confusión:** Revela si el modelo se confunde entre enfermedades visualmente similares (ej. Tizón vs Mancha Foliar).',
        'dash_report': '📑 Reporte de Clasificación Detallado (Classification Report)',
        'dash_roc': '📈 Curva ROC y AUC',
        'dash_cv': '📦 Robustez (Cross-Validation 5-Folds)'
    },
    'en': {
        'title': '🍅 Tomato Leaf Disease Detection System',
        'subtitle': 'Comparison of Classic and Hybrid Deep Learning models for automatic diagnosis',
        'sidebar_title': '⚙️ Configuration',
        'lang_select': '🌐 Language',
        'mode_select': '🚀 Analysis Mode',
        'mode_fast': 'Fast (Classics)',
        'mode_full': 'Full (Hybrids + Classics)',
        'mode_fast_desc': 'Ideal for mobile devices or instant predictions.',
        'mode_full_desc': 'Maximum precision. Includes SVM and Random Forest.',
        'tab_inference': '🔬 Smart Analysis',
        'tab_dashboard': '📊 Global Dashboard',
        'tab_stats': '📐 Statistical Tests',
        'tab_eda': '📈 Exploratory Data Analysis (EDA)',
        'tab_train': '⚙️ Model Laboratory',
        'tab_chat': '🤖 Virtual Assistant',
        'inference_desc': 'Upload an image of a tomato leaf to get a diagnosis based on the consensus of all our models.',
        'upload_img': '📸 Upload Image',
        'upload_label': 'Select a tomato leaf image',
        'btn_analyze': '🔍 Analyze Image',
        'loading': 'Analyzing with',
        'consensus_title': '👑 Final Prediction (Confidence Consensus)',
        'severity': 'Severity',
        'confidence_acc': 'Accumulated Confidence',
        'treatment_btn': '🛡️ View Recommended Treatment',
        'water': 'Watering',
        'chem': 'Chemical',
        'prev': 'Prevention',
        'model_details': '🤖 Model Details and Heatmaps',
        'prediction': 'Prediction',
        'heat_btn': 'Generate Heatmap for',
        'export_title': '📄 Export Reports',
        'btn_pdf': 'Download PDF',
        'btn_word': 'Download Word',
        'btn_excel': 'Download Excel',
        
        # Training Tab
        'train_title': '⚙️ Training Laboratory (PyTorch)',
        'train_desc': 'Train neural networks in real-time from the browser. Hyperparameters will impact the live process.',
        'train_settings': 'Training Parameters',
        'train_epochs': 'Epochs',
        'train_lr': 'Learning Rate',
        'train_batch': 'Batch Size',
        'train_model': 'Base Model',
        'btn_start_train': '🚀 Start Training',
        'training_progress': 'Training Progress',
        'epoch': 'Epoch',
        'loss': 'Loss',
        'accuracy': 'Accuracy',
        'train_done': 'Training Finished! Model saved.',
        
        # Chatbot
        'chat_title': '🤖 Virtual Agronomist Assistant',
        'chat_desc': 'Ask me questions about tomato diseases, treatments, or how to use this system.',
        'chat_input': 'Type your question here...',
        'chat_welcome': 'Hello! I am your virtual agronomist assistant. How can I help you today?',
        
        # Errors & Warnings
        'err_no_img': 'Please upload an image first.',
        'err_heat': 'Heatmaps are not available for hybrid models.',
        'err_predict': 'Error during prediction',
        
        # Dashboard
        'dash_title': '📊 Global Performance Dashboard',
        'dash_desc': 'Comprehensive view of performance metrics, validation, and discriminative capacity.',
        'dash_hist': '📈 Training History (Accuracy vs Loss)',
        'dash_hist_info': '💡 **Learning Curves:** Demonstrates that the model converged correctly without suffering from Overfitting.',
        'dash_cm': '🎯 Confusion Matrix (Ensemble)',
        'dash_cm_info': '💡 **Confusion Matrix:** Reveals if the model confuses visually similar diseases (e.g. Early vs Late Blight).',
        'dash_report': '📑 Detailed Classification Report',
        'dash_roc': '📈 ROC Curve and AUC',
        'dash_cv': '📦 Robustness (Cross-Validation 5-Folds)'
    }
}
